### ISSUE TITLE
Erreur javascript edition de métadonnée

### ISSUE THREAD

**Issue by Fonaine** [geosource-catalogue/core-geonetwork#222]
Lors de l'édition de métadonnée contenant une emprise dont une borne est comprise entre -1 et 1, une erreur javascript se produit à l'enregistrement de la fiche e bloque celui-ci. 
![edit_metadata2](https://cloud.githubusercontent.com/assets/238629/7139993/6a33ff3e-e2c9-11e4-95cb-5ef2385f950b.png)

Problème reproduit sur une version installée sous window7 et une version tomcat/postgresql

**Comment by fxprunayre** [comment]
Je n'observe pas le problème
![image](https://cloud.githubusercontent.com/assets/1701393/7175567/6222f900-e416-11e4-80ab-7a3995c7b930.png)

Vous pouvez lancer l'appli avec catalog.edit?debug et ajouter au ticket l'erreur JS. Merci

**Comment by Fonaine** [comment]
Bonjour,

Voici l'erreur js : 
SyntaxError: Unexpected token .
    at Object.parse (native)
    at Object.fromJson (http://localhost:8080/geosource/catalog/lib/angular/angular.js:1035:14)
    at Object.onFormLoad (http://localhost:8080/geosource/catalog/components/metadatamanager/EditorService.js:271:24)
    at Scope.module.controller.$scope.onFormLoad (http://localhost:8080/geosource/catalog/js/edit/EditorController.js:235:18)
    at Parser.functionCall (http://localhost:8080/geosource/catalog/lib/angular/angular.js:10168:21)
    at Scope.$get.Scope.$eval (http://localhost:8080/geosource/catalog/lib/angular/angular.js:11906:28)
    at http://localhost:8080/geosource/catalog/lib/angular/angular.js:18522:21
    at http://localhost:8080/geosource/catalog/lib/angular/angular.js:7553:11
    at deferred.promise.then.wrappedCallback (http://localhost:8080/geosource/catalog/lib/angular/angular.js:10905:81)
    at deferred.promise.then.wrappedCallback (http://localhost:8080/geosource/catalog/lib/angular/angular.js:10905:81)

Je précise que le bug est sur geosource 2.11.1.

![export1](https://cloud.githubusercontent.com/assets/238629/7248477/37430120-e813-11e4-89ae-2d64042e41db.png)

**Comment by fxprunayre** [comment]
Le formattage des nombres se faisait sans 0 pour la partie entière (eg. ,5 au lieu de 0,5) ce qui était à l'origine de l'erreur.

Cf. https://github.com/geosource-catalogue/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/layout/utility-tpl.xsl#L12
