### ISSUE TITLE
Lien donnée Service

### ISSUE THREAD

**Issue by delobelle** [geosource-catalogue/core-geonetwork#33]
En edition de MD, choisir dans "Ressource Associées" un servic eexistant et cliquer sur ajouter = renvoit un message d'erreur

Log : 

```
2014-01-21 15:42:19,669 ERROR [jeeves.service] - Exception executing gui service : java.lang.NullPointerException
2014-01-21 15:42:19,670 ERROR [jeeves.service] -  (C) Stack trace is :
java.lang.NullPointerException
                at org.fao.geonet.services.region.ThesaurusRequest.<init>(ThesaurusRequest.java:49)
                at org.fao.geonet.services.region.ThesaurusBasedRegionsDAO.createSearchRequest(ThesaurusBasedRegionsDAO.java:52)
                at org.fao.geonet.services.region.List.exec(List.java:61)
                at org.fao.geonet.guiservices.regions.Get.exec(Get.java:51)
                at jeeves.server.dispatchers.guiservices.Call.exec(Call.java:81)
                at jeeves.server.dispatchers.AbstractPage.invokeGuiService(AbstractPage.java:116)
                at jeeves.server.dispatchers.AbstractPage.invokeGuiServices(AbstractPage.java:105)
                at jeeves.server.dispatchers.ServiceManager.dispatchOutput(ServiceManager.java:748)
                at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:450)
                at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:362)
                at jeeves.server.JeevesEngine.dispatch(JeevesEngine.java:806)
                at jeeves.server.sources.http.JeevesServlet.execute(JeevesServlet.java:216)
                at jeeves.server.sources.http.JeevesServlet.doGet(JeevesServlet.java:115)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.fao.geonet.monitor.webapp.WebappMetricsFilter.doFilter(WebappMetricsFilter.java:96)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.fao.geonet.monitor.webapp.MetricsRegistryInitializerFilter.doFilter(MetricsRegistryInitializerFilter.java:31)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
                at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
                at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
                at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:322)
                at jeeves.config.springutil.GeonetworkFilterSecurityInterceptor.invoke(GeonetworkFilterSecurityInterceptor.java:46)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at jeeves.config.springutil.GeonetworkFilterSecurityInterceptor.invoke(GeonetworkFilterSecurityInterceptor.java:46)
                at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.fao.geonet.kernel.security.PassthroughFilter.doFilter(PassthroughFilter.java:26)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
                at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
                at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:184)
                at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:155)
                at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
                at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
                at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
                at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
                at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
                at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
                at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
                at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
                at java.lang.Thread.run(Thread.java:744)
```

**Comment by delobelle** [comment]
Erreur qui se reproduit quand on cherche à associer d'autres ressources : 

ex : associer une ressource en ligne ; associer une fiche parent, associer un jeu de données etc...

**Comment by fxprunayre** [comment]
L'erreur est en lien avec org.fao.geonet.services.region.ThesaurusRequest donc a priori rien à voir avec l'association de ressource. Est-ce que les associations fonctionnent bien ? de mon côté ça semble ok.

**Comment by taffoureau** [comment]
Résolu. C'était en fait un problème de configuration des schemas dans le data.directory.
