### ISSUE TITLE
[2.9.2] csw-Harvest

### ISSUE THREAD

**Issue by taffoureau** [geosource-catalogue/core-geonetwork#42]
Requête :

```
<?xml version="1.0" encoding="UTF-8"?>
<csw:Harvest service="CSW" version="2.0.2" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-publication.xsd">
    <csw:Source>http://metadata.carmencarto.fr/geosource-119/srv/fre/csw?service=CSW&REQUEST=GetCapabilities&version=2.0.2</csw:Source>
    <csw:ResourceType>http://www.isotc211.org/schemas/2005/gmd/</csw:ResourceType>

    <csw:ResourceFormat>application/xml</csw:ResourceFormat>

    <!-- Harvest interval ISO8601 period format (run every day) -->
    <!-- <csw:HarvestInterval>P0Y0M1DT0H0M0S</csw:HarvestInterval> -->

    <!-- Handler to process request asynchronously  -->
    <!-- <csw:ResponseHandler>mailto:anymail@domain.net</csw:ResponseHandler> -->
 </csw:Harvest>
```

Erreur :

```
2014-01-21 17:20:36,704 INFO  [jeeves.request] - HTML Request (from 193.56.4.66) : /geosource/srv/fre/csw-publication
2014-01-21 17:20:36,707 ERROR [jeeves.request] - Cannot build ServiceRequest
Cause : Error on line 5: The reference to entity "REQUEST" must end with the ';' delimiter.
Error : org.jdom.input.JDOMParseException
Stack :
org.jdom.input.JDOMParseException: Error on line 5: The reference to entity "REQUEST" must end with the ';' delimiter.
    at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
    at org.jdom.input.SAXBuilder.build(SAXBuilder.java:770)
    at jeeves.utils.Xml.loadStream(Xml.java:360)
    at jeeves.server.sources.ServiceRequestFactory.extractXmlParamet
[...]
```

**Comment by fxprunayre** [comment]
Un document XML ne peut contenir des caractères "&". Ce doit être "&amp;". La requête n'est pas bien formé. Le support de la méthode Harvest est loin d'être complet dans GN - cf. dev fait dans GéoSource il y 4 ou 5 ans.
