### ISSUE TITLE
Erreur moissonnage opendata sie

### ISSUE THREAD

**Issue by fxprunayre** [geosource-catalogue/core-geonetwork#50]
URL moissonnée :
http://www.data.eaufrance.fr/geosource/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
Logs :

GET params:request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns%28csw%3Dhttp%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2%29%2Cxmlns%28gmd%3Dhttp%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd%29&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&startPosition=1&maxRecords=20&elementSetName=summary&constraint=csw%3AAnyText+%3D+%27eau%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=gmd%3AMD_Metadata%2Ccsw%3ARecord
2014-02-14 11:08:08,889 WARN  [geonetwork.harvester] - Raised exception when searching : org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=outputFormat, message=application%2Fxml
POST params:<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata,csw:Record">
    csw:ElementSetNamesummary/csw:ElementSetName
    <csw:Constraint version="1.1.0">
      <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
        ogc:PropertyIsEqualTo
          ogc:PropertyNamecsw:AnyText/ogc:PropertyName
          ogc:Literaleau/ogc:Literal
        /ogc:PropertyIsEqualTo
      /ogc:Filter
    /csw:Constraint
  /csw:Query
/csw:GetRecords
2014-02-14 11:08:08,892 WARN  [geonetwork.harvester] - Raised exception when searching : org.jdom.input.JDOMParseException: Error on line 1: White spaces are required between publicId and systemId.
2014-02-14 11:08:08,892 WARN  [geonetwork.harvester] - Raised exception while harvesting from : opendata sie (CswHarvester)
2014-02-14 11:08:08,892 WARN  [geonetwork.harvester] -  (C) Class   : OperationAbortedEx
2014-02-14 11:08:08,892 WARN  [geonetwork.harvester] -  (C) Message : Raised exception when searching: Error on line 1: White spaces are required between publicId and systemId.
OperationAbortedEx : Raised exception when searching: Error on line 1: White spaces are required between publicId and systemId.
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.doSearch(Harvester.java:554)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.search(Harvester.java:237)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:109)
    at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:243)
    at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:401)
    at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:454)
    at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:29)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
result [Element: <node/>]
result [Element: <node/>]
GET params:request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns%28csw%3Dhttp%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2%29%2Cxmlns%28gmd%3Dhttp%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd%29&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&startPosition=1&maxRecords=20&elementSetName=summary&constraint=csw%3AAnyText+%3D+%27eau%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=gmd%3AMD_Metadata%2Ccsw%3ARecord
2014-02-14 14:46:28,157 WARN  [geonetwork.harvester] - Raised exception when searching : org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=outputFormat, message=application%2Fxml
POST params:<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" service="CSW" version="2.0.2" resultType="results" outputFormat="application/xml" outputSchema="http://www.isotc211.org/2005/gmd" startPosition="1" maxRecords="20">
  <csw:Query typeNames="gmd:MD_Metadata,csw:Record">
    csw:ElementSetNamesummary/csw:ElementSetName
    <csw:Constraint version="1.1.0">
      <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
        ogc:PropertyIsEqualTo
          ogc:PropertyNamecsw:AnyText/ogc:PropertyName
          ogc:Literaleau/ogc:Literal
        /ogc:PropertyIsEqualTo
      /ogc:Filter
    /csw:Constraint
  /csw:Query
/csw:GetRecords
2014-02-14 14:46:28,160 WARN  [geonetwork.harvester] - Raised exception when searching : org.jdom.input.JDOMParseException: Error on line 1: White spaces are required between publicId and systemId.
2014-02-14 14:46:28,160 WARN  [geonetwork.harvester] - Raised exception while harvesting from : opendata sie (CswHarvester)
2014-02-14 14:46:28,160 WARN  [geonetwork.harvester] -  (C) Class   : OperationAbortedEx
2014-02-14 14:46:28,160 WARN  [geonetwork.harvester] -  (C) Message : Raised exception when searching: Error on line 1: White spaces are required between publicId and systemId.
OperationAbortedEx : Raised exception when searching: Error on line 1: White spaces are required between publicId and systemId.
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.doSearch(Harvester.java:554)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.search(Harvester.java:237)
    at org.fao.geonet.kernel.harvest.harvester.csw.Harvester.harvest(Harvester.java:109)
    at org.fao.geonet.kernel.harvest.harvester.csw.CswHarvester.doHarvest(CswHarvester.java:243)
    at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester$HarvestWithIndexProcessor.process(AbstractHarvester.java:401)
    at org.fao.geonet.kernel.harvest.harvester.AbstractHarvester.harvest(AbstractHarvester.java:454)
    at org.fao.geonet.kernel.harvest.harvester.HarvesterJob.execute(HarvesterJob.java:29)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

**Comment by fxprunayre** [comment]
Testé avec le mots clés WISE. Semble ok.
